// Section-scoped llms.txt, e.g. /reference/llms.txt, /guides/llms.txt.
// The root /llms.txt (from starlight-llms-txt) and /llms-full.txt cover the
// whole corpus; these give an agent working a narrow task a small, cheap index
// of just one section instead of pulling the ~566 KB full file. Each entry links
// to the page's raw markdown (append-.md route in src/pages/[...slug].md.ts).
import type { APIRoute, GetStaticPaths } from 'astro';
import { getCollection } from 'astro:content';
import { SITE } from '../../../site.config.mjs';

// The autogenerated content sections that get their own scoped index.
const SECTIONS: Record<string, string> = {
  reference: 'Reference',
  guides: 'Guides',
  playbooks: 'VC playbooks',
  projects: 'Open-source projects',
  notes: 'Field notes',
  learn: 'Learn · The 80x Method',
};

export const getStaticPaths: GetStaticPaths = () =>
  Object.keys(SECTIONS).map((section) => ({ params: { section } }));

export const GET: APIRoute = async ({ params }) => {
  const section = params.section as string;
  const label = SECTIONS[section];

  const docs = await getCollection('docs');
  const pages = docs
    .filter(
      (d) =>
        typeof d.body === 'string' &&
        (d.id === section || d.id.startsWith(`${section}/`))
    )
    // section index (id === section, or `${section}/index`) first, then A–Z.
    .sort((a, b) => {
      const ai = a.id === section || a.id.endsWith('/index');
      const bi = b.id === section || b.id.endsWith('/index');
      if (ai !== bi) return ai ? -1 : 1;
      return a.data.title.localeCompare(b.data.title);
    });

  const lines = [
    `# ${SITE.name}: ${label}`,
    '',
    `> ${label} section of ${SITE.name}. ${SITE.tagline}.`,
    '',
    'Append `.md` to any URL below for its raw markdown. Full corpus: ' +
      `${SITE.docsUrl}/llms-full.txt`,
    '',
    `## ${label}`,
    '',
    ...pages.map((p) => {
      const url = `${SITE.docsUrl}/${p.id}/`;
      const desc = p.data.description ? `: ${p.data.description}` : '';
      return `- [${p.data.title}](${url})${desc}`;
    }),
    '',
  ];

  return new Response(lines.join('\n'), {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'cache-control': 'public, max-age=0, s-maxage=3600, stale-while-revalidate=86400',
    },
  });
};
